# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache-AxKit-Provider-XMLDOMProvider
version:      0.03
version_from: lib/Apache/AxKit/Provider/XMLDOMProvider.pm
installdirs:  site
requires:
    Apache:                        0
    AxKit:                         0
    LWP::UserAgent:                0
    Time::Piece:                   0
    XML::LibXML:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
